# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: grab
channels:
  - pyg
  - nvidia # for CUDA
  - pytorch
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pip~=23.1.2
  - cudatoolkit=11.8
  - pytorch-cuda=11.8
  - cudnn~=8.8.0 # https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html
  - psutil
  - python-dotenv
  - ruamel.yaml
  - tqdm

  # Frameworks
  - numpy~=1.25.1
  - scipy
  - pandas
  - openpyxl # to open excel files
  - pandarallel # for parallel computing panda dataframe

  # scikit-learn
  - scikit-learn
  - scikit-image

  # PyTorch
  - pytorch~=2.0.1
  - torchvision~=0.15.2
  - pytorch-sparse~=0.6.17

  # Huggingface
  - transformers~=4.29.0
  - datasets~=2.12.0
  - accelerate~=0.19.0
  - tokenizers>=0.13.1 # https://stackoverflow.com/a/74386742

  # utils
  - absl-py # for logging
  - overrides
  - torchmetrics
  - torchinfo
  - bayesian-optimization

  # Visualization
  - matplotlib
  - seaborn
  - moviepy # for generating gif

  # Development
  - jupyter
  - wandb

  # PyPI common practice
  - click
  - setuptools-scm
  - twine # for uploading to pypi
  - blackd # black daemon, for python formatting
  - mypy # for type checking
  - bump2version # for version bump
  - watchdog # filesystem event
  - flake8 # linter
  - tox
  - coverage
  - sphinx # doc

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - build
      - nvitop # for monitoring GPU usage
      - sourcery
      - singleton-decorator
      - torchopt~=0.7.0
      - evaluate~=0.4.0
      - peft~=0.4.0
      - loralib==0.1.1
      - separableconv-torch
      - kmeans1d # for k-means quantization
