# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: grab
channels:
  - pyg
  - nvidia # for CUDA
  - pytorch
  - huggingface
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pip~=23.1.2
  - cudatoolkit=11.8
  - pytorch-cuda=11.8
  - cudnn~=8.8.0 # https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html
  - psutil
  - python-dotenv
  - ruamel.yaml
  - omegaconf # for config
  - tqdm
  - attrs
  - tabulate

  # Frameworks
  - numpy~=1.25.1
  - scipy
  - pandas
  - openpyxl # to open excel files
  - pandarallel # for parallel computing panda dataframe
  - cvxpy

  # scikit-learn
  - scikit-learn
  - scikit-image

  # PyTorch
  - pytorch~=2.1.2
  - torchvision~=0.16.0
  - lightning~=2.1.2
  - pytorch-lightning~=2.1.2
  - pytorch-sparse~=0.6.18

  # Huggingface
  - transformers~=4.33.3
  - datasets~=2.14.5
  - accelerate~=0.23.0
  - tokenizers>=0.13.1 # https://stackoverflow.com/a/74386742

  # utils
  - absl-py # for logging
  - overrides
  - typed-argument-parser # for type hinting in argparse
  - jsonargparse
  - torchmetrics # lighting metrics
  - torchinfo
  - bayesian-optimization
  - hydra-core # for config using CLI

  # Visualization
  - matplotlib
  - seaborn
  - moviepy # for generating gif

  # Development
  - jupyter
  - wandb
  - tensorboard
  - tensorboardx

  # PyPI common practice
  - click
  - setuptools-scm
  - twine # for uploading to pypi
  - blackd # black daemon, for python formatting
  - mypy # for type checking
  - bump2version # for version bump
  - watchdog # filesystem event
  - flake8 # linter
  - tox
  - coverage
  - sphinx # doc

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - build
      - nvitop # for monitoring GPU usage
      - sourcery
      - singleton-decorator
      - torchopt~=0.7.2
      - evaluate~=0.4.1
      - peft~=0.5.0
      - loralib==0.1.2
      - separableconv-torch
      - kmeans1d # for k-means quantization
      - cd2root
      - lightning[pytorch-extra]
      - jsonargparse[signatures]>=4.18.0 # lightning cli
      # Trial
      - omegaconf-argparse # to use omegaconf with argparse
