#!/bin/bash
#SBATCH -o logs/%x.out               # output file (%j expands to jobID)
#SBATCH -e logs/%j.err               # error log file (%j expands to jobID)
#SBATCH -N 1                                 # Total number of nodes requested
#SBATCH -n 16                                 # Total number of cores requested
#SBATCH --get-user-env                       # retrieve the users login environment
#SBATCH --mem=64g                            # server memory requested (per node)
#SBATCH -t 08:00:00                           # Time limit (hh:mm:ss)
#SBATCH --partition=gpu,desa                     # Request partition
#SBATCH --gres=gpu:1                  # Type/number of GPUs needed


echo %x
echo hello

sleep 10

